In [346]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import permutations, combinations, islice
from itertools import islice

In [370]:
def gen_pi(n = 4, v = 20):
    while True:
        pi_0 = np.random.uniform(size=n)
        pisum = np.sum(pi_0)
        pi = [i/pisum for i in pi_0]
        Nv = [int(round(i*v)) for i in pi]
        if not 0 in Nv and np.sum(Nv)==v:
            break
    return pi, Nv

pi, Nv = gen_pi(4)
print(pi, '=', np.sum(pi))
print(Nv)

[0.3031310728495155, 0.13498230146693121, 0.16327936724543918, 0.39860725843811395] = 0.9999999999999998
[6, 3, 3, 8]


In [371]:
def gen_blockprob(n = 4):
    blockprob = np.zeros((n,n))
    for i in range(n):
        for j in range(i,n):
            blockprob[i,j] = np.random.uniform()
            blockprob[j,i] = np.random.uniform()
    return blockprob

blockprob = gen_blockprob(4)
print(blockprob)

[[0.94766363 0.01491104 0.66105803 0.22935952]
 [0.20172588 0.06677707 0.21321127 0.78630652]
 [0.71497726 0.59940808 0.48944716 0.87367782]
 [0.07675084 0.45816586 0.27610564 0.34000449]]


In [377]:
def gen_adj(pi, Nv, blockprob):
    v = np.sum(Nv)
    adj = np.zeros((v,v))
    
    def ind_to_block(i):
        block = -1
        while i >= 0:
            block += 1
            i -= Nv[block]
        return block

    for i in range(v):
        for j in range(i,v):
            val = np.random.binomial(1, blockprob[ind_to_block(i), ind_to_block(j)])
            adj[i,j] = val
            adj[j,i] = val
    np.fill_diagonal(adj,0)
    return adj

adj = gen_adj(pi, Nv, blockprob)
print(adj)
print(adj.shape)

[[0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.

In [396]:
def likelihood(Nv):
    def ind_to_block(i):
        block = -1
        while i >= 0:
            block += 1
            i -= Nv[block]
        return block
    #def gen_e():
        #gen a kxk matrix e
    numerator_sum = 0
    denominator_sum = 0
    numerator_perms = []
    n = int(np.sum(Nv))
    counter = 0
    for i in permutations(range(n),n):
        print(i)
        V = [i[int(sum(Nv[:j])):int(sum(Nv[:j+1]))] for j in range(len(Nv))]
        print(V)
        counter += 1
        if counter > 5:
            break
    #use v and ind_to_block to generate e
    #then use e and lambda to find the likelihood with a nested multiplication

In [397]:
likelihood([4,2,1])

(0, 1, 2, 3, 4, 5, 6)
[(0, 1, 2, 3), (4, 5), (6,)]
(0, 1, 2, 3, 4, 6, 5)
[(0, 1, 2, 3), (4, 6), (5,)]
(0, 1, 2, 3, 5, 4, 6)
[(0, 1, 2, 3), (5, 4), (6,)]
(0, 1, 2, 3, 5, 6, 4)
[(0, 1, 2, 3), (5, 6), (4,)]
(0, 1, 2, 3, 6, 4, 5)
[(0, 1, 2, 3), (6, 4), (5,)]
(0, 1, 2, 3, 6, 5, 4)
[(0, 1, 2, 3), (6, 5), (4,)]


In [141]:
def split_by_lengths(seq, num):
    it = iter(seq)
    out =  [x for x in (list(islice(it, n)) for n in num) if x]
    remain = list(it)
    return out if not remain else out + [remain]

In [144]:
split_by_lengths([0,1,2,3,4,5,6], [4,2,1])

[[0, 1, 2, 3], [4, 5], [6]]