In [1]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import permutations, combinations, combinations_with_replacement, islice
from itertools import islice

In [2]:
def gen_pi(n = 4, v = 20):
    while True:
        pi_0 = np.random.uniform(size=n)
        pisum = np.sum(pi_0)
        pi = [i/pisum for i in pi_0]
        Nv = [int(round(i*v)) for i in pi]
        if not 0 in Nv and np.sum(Nv)==v:
            break
    return pi, Nv

pi, Nv = gen_pi(4)
print(pi, '=', np.sum(pi))
print(Nv)

[0.36698675334869435, 0.28619658483078236, 0.3077152813399075, 0.03910138048061589] = 1.0000000000000002
[7, 6, 6, 1]


In [3]:
def gen_blockprob(n = 4):
    blockprob = np.zeros((n,n))
    for i in range(n):
        for j in range(i,n):
            blockprob[i,j] = np.random.uniform()
            blockprob[j,i] = np.random.uniform()
    return blockprob

blockprob = gen_blockprob(4)
print(blockprob)

[[0.90663773 0.1267139  0.34836903 0.71626187]
 [0.43956529 0.7615279  0.4730221  0.62153505]
 [0.78211068 0.30829512 0.77297593 0.77792221]
 [0.77451605 0.94247903 0.61122934 0.99775156]]


In [4]:
def gen_adj(pi, Nv, blockprob):
    v = np.sum(Nv)
    adj = np.zeros((v,v))
    
    def ind_to_block(i):
        block = -1
        while i >= 0:
            block += 1
            i -= Nv[block]
        return block

    for i in range(v):
        for j in range(i,v):
            val = np.random.binomial(1, blockprob[ind_to_block(i), ind_to_block(j)])
            adj[i,j] = val
            adj[j,i] = val
    np.fill_diagonal(adj,0)
    return adj

adj = gen_adj(pi, Nv, blockprob)
print(adj)
print(adj.shape)

[[0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1.

In [7]:
adj = np.ones((int(np.sum(Nv)),int(np.sum(Nv))))
np.fill_diagonal(adj,0)

In [16]:
import math
def choose(n, k): #hayden.ipynb
    if n<k:
        return 0
    else:
        num = math.factorial(n)
        den = math.factorial(k)*math.factorial(n - k)
        return num/den

In [18]:
def gen_e(adj, perm):
    k = len(perm)
    e = np.zeros((k,k))
    for i in range(k):
        for j in range(i, k):
            for v in perm[i]:
                for s in perm[j]:
                    e[i,j] += adj[v, s]
                    e[j,i] += adj[v, s]
                    if i==j:
                        e[i,j] -= adj[v,s]
    return e

In [22]:
def gen_c(Nv, e):
    k = len(Nv)
    c = np.zeros((k,k))
    for i in range(k):
        for j in range(i, k):
            if i==j:
                c[i,j] = choose(Nv[i],2) - e[i,j]
            else:
                c[i,j] = (Nv[i]*Nv[j]) - e[i,j]
                c[j,i] = (Nv[i]*Nv[j]) - e[i,j]
    return c

In [23]:
def likelihood(Nv):
    numerator_sum = 0
    denominator_sum = 0
    numerator_perms = []
    n = int(np.sum(Nv))
    counter = 0
    for i in permutations(range(n),n):
        print(i)
        perm = [i[int(sum(Nv[:j])):int(sum(Nv[:j+1]))] for j in range(len(Nv))]
        print(perm)
        e = gen_e(adj, perm)
        print(e)
        c = gen_c(Nv, e)
        print(c)
        counter += 1
        if counter>5:
            break
    #use v and ind_to_block to generate e
    #then use e and lambda to find the likelihood with a nested multiplication

In [24]:
print(adj)
likelihood(Nv)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.

In [ ]:
def split_by_lengths(seq, num):
    it = iter(seq)
    out =  [x for x in (list(islice(it, n)) for n in num) if x]
    remain = list(it)
    return out if not remain else out + [remain]

In [144]:
split_by_lengths([0,1,2,3,4,5,6], [4,2,1])

[[0, 1, 2, 3], [4, 5], [6]]